### ISSUE TITLE
have a question with oom on android

### ISSUE THREAD

**Issue by zhushenwudi** [pakerwreah/Inspector#45]
When I call an interface or print a large text string, he may collapse.The system will kill the process and collapse on the C ++ layer

**Comment by pakerwreah** [comment]
Can you attach a sample code that would do that?

**Comment by zhushenwudi** [comment]
This requires calling the network interface to appear. At present, this part of the business is the company's internal business, which is not very convenient for output sample code
I sent a 1M's text to the server, and the network request is concurrently not serial. See if your side can simulate my situation.

**Comment by pakerwreah** [comment]
I don't know what you mean by "call an interface" or "print a text".
Where are you "printing" this text? When are you calling this "interface"? Which "interface"?
Are you talking about a `WebSocket`, a `Plugin`, a `LivePlugin`, a `PluginAPI`?
What happens when it "collapses"? Do you get an error message in the console?

I'm not asking for your company's code, I'm just asking for **_some_** code da reproduces the issue so I can investigate.
Could you create a brand-new project and try to simulate your issue? That way we can pinpoint exactly where the problem is without any external influence.

**Comment by zhushenwudi** [comment]
ok, i will try to create a sample code and give you a download url

**Comment by zhushenwudi** [comment]
很遗憾。使用样例代码是无法复现出来的。可能因为内存使用比较少。
崩溃部分的代码的错误是oom，我们产品的cpu是rk3288，2G+16G
下面是崩溃信息
![1](https://user-images.githubusercontent.com/30340027/188050836-6e4a1032-88a4-42d4-bc4e-90aa0979503d.png)
我分别对使用和不使用inspect分别做了测试。结果是不使用是不会产生oom的，因为我们依赖了一个人脸验证框架，所以不能将demo交付给你
下面是没有使用inspect的内存使用情况
![iShot_2022-09-02_11 03 06](https://user-images.githubusercontent.com/30340027/188051109-394444ac-0ed8-4879-9015-7ab76528d12a.png)
由图可见，大概在人脸识别开启时会占用200m+的内存，虽然项目设置了largeheap，结果可能和硬件有关系吧

后面我会酌情考虑在内存使用率相对较少的项目中加入该库的

**Comment by pakerwreah** [comment]
Your log message was actually quite helpful, because it says that there's a problem creating new threads.
It probably comes down to your use case, but I will check if there's some thread leak in the C++ layer.

Can you tell me how long it takes to crash after you launch it? I want to know if it takes a short few seconds or a full minute.
Also, how many requests are you making? Like 1 per second, or are you spamming requests like crazy?

**Comment by zhushenwudi** [comment]
My program is a person's face recognition login system. After clicking the button, you will open a new activity, call the face recognition SDK, and the CPU and memory displayed in the Profiler Inspect will increase significantly, or even more than 200m memory overhead.After the authentication is passed, the network request is called. After the network request returns the result, the activity will be exited to release the memory of the face recognition SDK.When not use inspector library, you can see that the memory drops from the Profiler Inspect to the occupation before activity startup.It shows that the memory is not leaked. But when I use inspector library, the memory will be unstable and produce OOM

My sample code just simulates the login request, and all the parameters are consistent with the product code.But there was no collapse.I'm sorry I can't provide this part of the sample code.I am using AndroidGodeye now, and trying whether there are similar problems, it is still in the construction stage

**Comment by zhushenwudi** [comment]
There is no problem with once certification login. After the record of 6-10 times will happened, the memory release will occur.Two network http request will be called each time you log in. One is to get the company ID and the other is login

**Comment by pakerwreah** [comment]
Maybe there's not enough time for the garbage collection to free that memory before making the requests.
Thanks for the feedback! I will see if I can improve the stability in low memory conditions.

**Comment by zhushenwudi** [comment]
I built AndroidGodeye library. After meticulous test verification, there is no problem, and memory can be recycled normally.I hope inspector library can be better and better after being polished
